import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { GENERATED_DIR, collectTopics, loadPosts } from './lib/content.mjs';

const HEADER = '// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.\n\n';

const { posts, errors } = await loadPosts();

if (errors.length > 0) {
  console.error('Content generation failed:\n');
  for (const error of errors) console.error(`  ✗ ${error}`);
  process.exit(1);
}

const postsDir = path.join(GENERATED_DIR, 'posts');
await rm(GENERATED_DIR, { recursive: true, force: true });
await mkdir(postsDir, { recursive: true });

for (const post of posts) {
  const file = path.join(postsDir, `${post.slug}.ts`);
  const module =
    HEADER +
    `export const POST_HTML = ${JSON.stringify(post.html)};\n\n` +
    `export const POST_HEADINGS = ${JSON.stringify(post.headings)};\n\n` +
    `export const POST_SOURCES = ${JSON.stringify(post.sources)};\n`;
  await writeFile(file, module, 'utf8');
}

const metas = posts.map((post) => ({
  slug: post.slug,
  title: post.title,
  description: post.description,
  publishedAt: post.publishedAt,
  updatedAt: post.updatedAt,
  category: post.category,
  categorySlug: post.categorySlug,
  tags: post.tags,
  featured: post.featured,
  trending: post.trending,
  featuredOrder: post.featuredOrder,
  coverImage: post.coverImage,
  readingTimeMinutes: post.readingTimeMinutes,
  relatedSlugs: post.relatedSlugs,
}));

const { categories, tags } = collectTopics(posts);

const loaders = posts
  .map((post) => `  '${post.slug}': () => import('./posts/${post.slug}'),`)
  .join('\n');

const index =
  HEADER +
  `import type { ArticleSource, PostMeta, TocHeading, TopicInfo } from '../core/models/post.model';\n\n` +
  `export const POSTS: readonly PostMeta[] = ${JSON.stringify(metas, null, 2)};\n\n` +
  `export const CATEGORIES: readonly TopicInfo[] = ${JSON.stringify(categories, null, 2)};\n\n` +
  `export const TAGS: readonly TopicInfo[] = ${JSON.stringify(tags, null, 2)};\n\n` +
  `export const POST_LOADERS: Record<\n  string,\n  () => Promise<{ POST_HTML: string; POST_HEADINGS: TocHeading[]; POST_SOURCES: ArticleSource[] }>\n> = {\n${loaders}\n};\n`;

await writeFile(path.join(GENERATED_DIR, 'posts.generated.ts'), index, 'utf8');

console.log(`Generated ${posts.length} article(s), ${categories.length} categories, ${tags.length} tags.`);
